### PR TITLE
AdamW added with version checks

### PR DESCRIPTION
**Pull request by kiryteo**
Addressing #62 only including AdamW use based on version check.

### CODE REVIEW

**Comment by GilesStrong** [comment]
Hi @kiryteo thanks very much for this! I'm sorry it's taking me a while to check it; busy week and I'm moving country next week...
I'll try and get it checked and merged as soon as I can.
I noticed you'd also added a contribution guide. This would certainly be welcome, too. Could you possibly create a separate PR for it, though, so we can discuss and adjust it? Thanks!

**Comment by kiryteo** [comment]
Alright, no issues! I realized the single PR for both the commits and thus reverted the second commit, I'll add it as a separate PR.

**Comment by GilesStrong** [comment]
Hi @kiryteo sorry for the wait. I've made a few modifications to deal with the regularisation argument, and simplify a bit the version checking, but can't push them to your fork. Could you possibly enable "Allow edits from maintainers" for this PR? Otherwise I can send you the modified code. Thanks!

**Comment by kiryteo** [comment]
Hi @GilesStrong looks like the 'Allow edits' option is enabled.

**Comment by GilesStrong** [comment]
Ah, thanks. I'd been trying to push to a new branch to pull to your master. Let me know if you're happy with the changes. The regularisation keyword is `'weight_decay'`.

**Comment by kiryteo** [comment]
@GilesStrong Regarding the keyword, this was going to be my question, whether to add the 'regularizer' as a specific keyword or work with weight decay (so I kept the code commented), but thanks for the clarification. Also, I wasn't aware of LooseVersion, thanks! You can merge the PR I think.

**Comment by GilesStrong** [comment]
Juts ran some tests and fixed the version check, I'd forgotten one could not compare directly to a float.
It all seems to work find and the warnings show up where intended.
Thanks very much for the help!

**Comment by kiryteo** [comment]
Great.! :raised_hands:

**Pull request merged**
